# Generated by cpputils-cmake.
include /disk1/workstation/dev/httppost/build/CMakeFiles/VoiceSlave.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES}  -S ${CHK_SOURCES}