# Generated by cpputils-cmake.
include /disk1/workstation/dev/httppost/build/CMakeFiles/VoiceSlave.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CC} -o /dev/null ${C_FLAGS} ${C_DEFINES}  -S ${CHK_SOURCES}